version: 2

build:
   os: ubuntu-22.04
   tools:
      python:
         version: 3.11

sphinx:
   builder: html
   configuration: docs/source/conf.py

python:
   install:
      - requirements: requirements.txt
   system_packages: true

formats:
   - epub
   - pdf